### ISSUE TITLE
Feature request: Always open a new window if all current Safari windows are minimised

### ISSUE THREAD

**Issue by mattsheppard** [lapcat/PrivateWindow#1] opened 2023-12-12 08:21 UTC
Love the idea for this app - Thanks for making it!

No idea if you're interested in feature requests, and perhaps I ought to just fork and try to hack this up myself, but what you have is very adjacent to something which has always frustrated me.

If I open a link from some other app (for me it's usually NetNewsWire), but all current Safari windows are minimised (because they're for something I was researching a while back etc), I would love it if the policy could be to always open a new safari window rather than to un-minimise an existing one.

Seems like this should be possible with what you have by looking at the content of the Safari Window menu, in the last section, seeing if all window names are prefixed with a diamond symbol, and if so, triggering a New Window first.

Totally understand if you don't want to add more features and settings etc, but I'd find it super useful if it were available.

**Comment by lapcat** [comment] 2023-12-12 13:56
The app always opens a new Safari window. So to be clear, it seems that your request is for the app to _not_ open a new window if Safari is _not_ minimized.

The problem is that there's no API to determine whether a window is private or non-private, which is why the app always needs to open a new window. Thus, this request is out of scope for the app, and as you say, you would need to fork the project.

**Closed as not planned by lapcat** 2023-12-12 13:56 UTC
